export const LOADING_CLIENTS = "LOADING_CLIENTS";
export const GET_ALL_CLIENTS_SUCCESS = "GET_ALL_CLIENTS_SUCCESS";
export const GET_ALL_CLIENTS_FAIL = "GET_ALL_CLIENTS_FAIL";

export const ADD_NEW_CLIENTS_SUCCESS = "ADD_NEW_CLIENTS_SUCCESS";
export const ADD_NEW_CLIENTS_FAIL = "ADD_NEW_CLIENTS_FAIL";

export const LOGIN_CLIENT_SUCCESS = "LOGIN_CLIENT_SUCCESS";
export const LOGIN_CLIENT_FAIL = "LOGIN_CLIENT_FAIL";

export const GET_CURRENT_CLIENT_SUCCESS = " GET_CURRENT_CLIENT_SUCCESS";
export const GET_CURRENT_CLIENT_FAIL = " GET_CURRENT_CLIENT_FAIL";

export const LOGOUT = "LOGOUT";
