export const LOADING_PRODUCTS = "LOADING_PRODUCTS";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_FAIL = "GET_ALL_PRODUCTS_FAIL";

export const ADD_NEW_PRODUCTS_SUCCESS = "ADD_NEW_PRODUCTS_SUCCESS";
export const ADD_NEW_PRODUCTS_FAIL = "ADD_NEW_PRODUCTS_FAIL";
